import {
  simpleAngular,
  simpleGit,
  simpleJavascript,
  simpleTypescript,
  simpleIonic,
  simpleMongodb,
  simpleMysql,
  simpleReact,
  simpleTailwindcss,
  simpleBootstrap,
  simplePrimeng,
  simpleExpress,
  simpleNodedotjs,
  simplePostman,
  simpleGithub,
  simpleBitbucket,
  simpleJira,
  simpleCss,
  simpleHtml5,
  simplePostgresql,
  simplePostcss,
  simpleJest,
  simpleGraphql,
  simpleJson,
  simpleZod,
  simpleDocker,
} from '@ng-icons/simple-icons';

import { lucideBriefcase, lucideCodeSquare, lucideUser2 } from '@ng-icons/lucide';

export const ICONS = {
  lucideBriefcase,
  lucideCodeSquare,
  lucideUser2,
  simpleAngular,
  simpleGit,
  simpleJavascript,
  simpleTypescript,
  simpleIonic,
  simpleMongodb,
  simpleMysql,
  simpleReact,
  simpleTailwindcss,
  simpleBootstrap,
  simplePrimeng,
  simpleExpress,
  simpleNodedotjs,
  simplePostman,
  simpleGithub,
  simpleBitbucket,
  simpleJira,
  simpleCss,
  simpleHtml5,
  simplePostgresql,
  simplePostcss,
  simpleJest,
  simpleGraphql,
  simpleJson,
  simpleZod,
  simpleDocker,
} as const;
